# This is a basic workflow to help you get started with Actions
name: Publish GitHub Actions Basic workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
       
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads
        
        
           # Stage 1 Secret Scan
           
             # Runs a single command using the runners shell
      - name: Installing Trufflehog3 tool
        run: pip install trufflehog3
        
      - name: Running Trufflehog3 tool and output
        continue-on-error: true
        run: trufflehog3 ./ -f json -o outputforsecretscan.json
        
        #Stage 2 Running SAST Scan
      
      - name: Installing njscan SAST tool
        run: pip install njsscan
        
      
      - name: Running njscan SAST tool
        continue-on-error: true
        run: njsscan ./ -o nodevulnappoutput.json
        
        #Satge 3
      - name: Build the code
        run: echo "Build"
        
         #Satge 4
      - name: Staging Deploy
        run: echo "Staging Deploy"
        
        #Stage 5 Running DAST
        
        # Runs a single command using the runners shell
      - name: Installing zap Running DAST Scan
        continue-on-error: true
        run: | 
         java -version
         ls
         sudo apt-get update
         sudo docker pull owasp/zap2docker-stable
         sudo docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py \
         -t http://testphp.vulnweb.com -J zapscan.json
         
         #Stage 6
         - name: UAT Testing
         run: echo "UAT Testing"
         
          #Stage 7
         - name: Infra Scan
         run: echo "Infra Scan"
         
          #Stage 8
         - name: Compliance Scan
         run: echo "Compliance Scan"
         
         #Stage 9
         - name: Production Deployment
         run: echo "Production Deployment"
         
        
      - run: | 
         sudo cp nodevulnappoutput.json downloads
         sudo cp outputforsecretscan.json downloads
         
      - name:  Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v3
        with: 
          name: Scanresults
          path: downloads
          
          
